# Generated by Django 4.2.8 on 2023-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="size",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.size"
            ),
            preserve_default=False,
        ),
    ]
