# Generated by Django 4.2.8 on 2023-12-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_item_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="long_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="short_description",
            field=models.CharField(
                default="This is a test description", max_length=255
            ),
            preserve_default=False,
        ),
    ]
