# Generated by Django 4.2.8 on 2023-12-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_item_long_description_item_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
