# Generated by Django 4.2.8 on 2023-12-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered_date",
            field=models.DateTimeField(default="2002-02-02"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
