# Generated by Django 4.2.8 on 2023-12-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_order_ordered_date_alter_order_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="amount",
        ),
    ]
