# Generated by Django 4.2.8 on 2023-12-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_fees",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
